# Generated by Django 3.0.8 on 2020-09-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-title']},
        ),
    ]
