# Generated by Django 3.0.8 on 2020-09-03 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0002_auto_20200901_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='photograph',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
