# Generated by Django 3.0.8 on 2020-08-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200821_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='same_shipping_address',
            new_name='same_billing_address',
        ),
    ]
