# Generated by Django 3.0.8 on 2020-08-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200821_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='apartment',
            new_name='billing_first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='first_name',
            new_name='billing_last_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='last_name',
            new_name='billing_state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='billing_street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zipcode',
            new_name='billing_zipcode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='shipping_first_name',
        ),
        migrations.AddField(
            model_name='address',
            name='billing_apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_last_name',
            field=models.CharField(default='LastName', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_state',
            field=models.CharField(default='State', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_street',
            field=models.CharField(default='Street', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
