# Generated by Django 3.0.8 on 2020-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200821_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='billing_apartment',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='billing_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='shipping_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='shipping_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='shipping_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='shipping_street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='shipping_zipcode',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_zipcode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='shipping_apartment',
        ),
        migrations.RemoveField(
            model_name='address',
            name='shipping_country',
        ),
    ]
