# Generated by Django 3.0.8 on 2020-08-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200821_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zipcode',
        ),
    ]
