# Generated by Django 3.0.8 on 2020-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_address_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='11111', max_length=20),
            preserve_default=False,
        ),
    ]
