# Generated by Django 3.0.8 on 2020-08-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200824_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='device_id',
            new_name='device',
        ),
    ]
