# Generated by Django 3.0.8 on 2020-08-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200826_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='img_size',
            field=models.CharField(choices=[('5R', '5x7'), ('8R', '8x10'), ('11R', '11x14'), ('12S', '12x12'), ('16R', '16x20'), ('16S', '16x16'), ('18R', '18x24'), ('20R', '20x24')], default='5R', max_length=3),
        ),
    ]
