# Generated by Django 3.0.8 on 2020-08-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orderitem_img_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img_size',
        ),
    ]
