# Generated by Django 3.0.8 on 2020-08-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_item_img_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.CharField(choices=[('5R', '15'), ('8R', '20'), ('11R', '30'), ('12S', '25'), ('16R', '40'), ('16S', '35'), ('18R', '50'), ('20R', '65')], default='5R', max_length=3),
        ),
    ]
