# Generated by Django 3.0.8 on 2020-09-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-item']},
        ),
    ]
