# Generated by Django 3.0.8 on 2020-09-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200901_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='img_size',
            field=models.CharField(choices=[('5R', '5x7'), ('8R', '8x10'), ('11R', '11x14'), ('12S', '12x12'), ('16R', '16x20'), ('16S', '16x16'), ('18R', '18x24'), ('20R', '20x30')], default='5R', max_length=3),
        ),
    ]
