# Generated by Django 3.0.8 on 2020-09-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200902_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
