# Generated by Django 3.0.8 on 2020-09-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_payment_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='same_billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
